const SHEETS={ATTENDANCE:"Attendance",STUDENTS:"Students",NOTES:"Daily Notes",TEACHERS:"Teachers",ROSTER:"Roster",VOLUNTEERS:"Volunteers"};
function doGet(){return json_({ok:true,message:"Church Check-In API is running"});}
function doPost(e){try{const d=JSON.parse(e.postData.contents||"{}"),ss=SpreadsheetApp.getActiveSpreadsheet();
if(d.action==="checkin"){const r=d.record,g=r.group;ensure_(ss,SHEETS.ATTENDANCE,["ID","Student ID","Student Name","Parent Name","Phone","Age","Grade","Teacher Group","Attendance Date","Checked In At","Present","Present At"]).appendRow([r.id,r.studentId,r.studentName,r.parentName,r.phone,r.age,r.grade,g,r.date,r.checkedInAt,false,""]);ensure_(ss,SHEETS.STUDENTS,["Student ID","Student Name","Parent Name","Phone","Age","Grade","Teacher Group","Last Name"]).appendRow([r.studentId,r.studentName,r.parentName,r.phone,r.age,r.grade,g,r.studentName.trim().split(/\s+/).pop()]);return json_({ok:true})}
if(d.action==="markPresent"){const sh=ensure_(ss,SHEETS.ATTENDANCE,["ID","Student ID","Student Name","Parent Name","Phone","Age","Grade","Teacher Group","Attendance Date","Checked In At","Present","Present At"]),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(d.id)){sh.getRange(i+1,11,1,2).setValues([[true,new Date()]]);break}return json_({ok:true})}
if(d.action==="saveNotes"){const sh=ensure_(ss,SHEETS.NOTES,["Attendance Date","Notes","Last Updated"]);sh.appendRow([d.date,d.notes||"",new Date()]);return json_({ok:true})}
if(d.action==="addTeacher"){ensure_(ss,SHEETS.TEACHERS,["Teacher Name","Teacher Group"]).appendRow([d.name,d.group]);return json_({ok:true})}
if(d.action==="addRosterStudent"){const r=d.student;ensure_(ss,SHEETS.ROSTER,["Student ID","Student Name","Parent Name","Phone","Age","Grade","Teacher Group"]).appendRow([r.studentId,r.studentName,r.parentName,r.phone,r.age,r.grade,r.group]);return json_({ok:true})}
if(d.action==="addVolunteer"){const v=d.volunteer;ensure_(ss,SHEETS.VOLUNTEERS,["Volunteer ID","Volunteer Name","Date","Serving","Serving At","Other Location"]);SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SHEETS.VOLUNTEERS).appendRow([v.id,v.name,"","", "", ""]);return json_({ok:true})}
if(d.action==="saveVolunteerSchedule"){const s=d.schedule||{},sh=ensure_(ss,SHEETS.VOLUNTEERS,["Volunteer ID","Volunteer Name","Date","Serving","Serving At","Other Location"]),v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(d.volunteerId)&&String(v[i][2])===String(d.date)){sh.getRange(i+1,4,1,3).setValues([[!!s.serving,s.area||"",s.other||""]]);return json_({ok:true})}let name="";for(let i=1;i<v.length;i++)if(String(v[i][0])===String(d.volunteerId)){name=v[i][1];break}sh.appendRow([d.volunteerId,name,d.date,!!s.serving,s.area||"",s.other||""]);return json_({ok:true})}
return json_({ok:true})}catch(err){return json_({ok:false,error:String(err)})}}
function ensure_(ss,n,h){let sh=ss.getSheetByName(n);if(!sh)sh=ss.insertSheet(n);if(sh.getLastRow()===0)sh.appendRow(h);return sh}function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
